# Generated by Django 4.0.2 on 2022-03-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prescription', models.CharField(choices=[('Yes', 'Positive'), ('No', 'Negative')], default='Yes', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('dateOrdered', models.CharField(max_length=30)),
                ('delivered', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('dateOrdered', models.CharField(max_length=30)),
                ('expectedDeliveryDate', models.CharField(max_length=30)),
                ('currentStatus', models.CharField(max_length=30)),
            ],
        ),
    ]
