# Generated by Django 4.0.3 on 2022-03-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthappdata', '0003_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartItemsNumber', models.IntegerField()),
            ],
        ),
    ]
