# Generated by Django 4.0.3 on 2022-03-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthappdata', '0004_cartnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartnumber',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
